version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/entrypoint:/docker-entrypoint-initdb.d
